Issue #39 - Add release like to readme.md
LinuxForHealth/cdm-fhir-ig pull request #41
Opened 2021-08-02 12:38 UTC by coxstuart

Adding release notes automation

- Add automated release notes generation when release is created
- Add release notes to readme

2021-08-02 14:11 UTC, dmangum2 requested changes
One change requested.

2021-08-02 14:11 UTC, dmangum2 commented on README.md
> +View the [Release][https://github.com/Alvearie/alvearie-fhir-ig/releases]. Each release includes the full IG specication.
"specication" typo.

2021-08-02 14:45 UTC, dmangum2 commented on README.md
> +View the [Release][https://github.com/Alvearie/alvearie-fhir-ig/releases]. Each release includes the full IG specication.
Also on the readme.md, looks strange.  (see Preview tab) ![image](https://user-images.githubusercontent.com/85960782/127879926-f52b7a52-811b-40a3-999b-886f16a33d21.png)

2021-08-02 16:25 UTC, coxstuart commented on README.md
> +View the [Release][https://github.com/Alvearie/alvearie-fhir-ig/releases]. Each release includes the full IG specication.
Thank you.  Fixed the typos and added some more content.

2021-08-02 18:14 UTC, coxstuart commented
> Issue labels "will" create? Or "are created on ...."

@dmangum2:  Thank you!  I fixed multiple typos and rewrote a bunch of the readme.  Please take another look.  I need "gramerly for git". Do they make that?

2021-08-02 19:12 UTC, dmangum2 approved these changes
Looks good!

2021-08-02 20:58 UTC, kimkenna commented
Two typos in the readme I believe:
1. Line 37 is missing an 's' for the word Issues in this line: "* Issue are used to document changes included in the release notes for each release"
2. Line 55 is missing the preceding e for export in this line: "xport GREN_GITHUB_TOKEN=<YOUR TOKEN HERE>"

2021-08-03 14:25 UTC, coxstuart commented
> Two typos in the readme I believe:
> 
> 1. Line 37 is missing an 's' for the word Issues in this line: "* Issue are used to document changes included in the release notes for each release"
> 2. Line 55 is missing the preceding e for export in this line: "xport GREN_GITHUB_TOKEN="

Thanks @kimkenna.  Sharp eyes!  Fixed the readme.

2021-08-03 20:28 UTC, dmangum2 requested changes
I had a few comments.

2021-08-03 20:28 UTC, dmangum2 commented on README.md
> +Changes must be made to the following files to version the IG. This will ensure the automatmed releases work correctly.
automatmed misspelled

2021-08-03 20:28 UTC, dmangum2 commented on README.md
> +1. **New major versions on breaking changes**
Should we note the version number scheme as N.x.x, so it's clear what pattern we are going to use?

2021-08-03 20:28 UTC, dmangum2 commented on README.md
> +2. **New minor version on non-breaking IG profile changes**
Note the version number pattern, like x.N.x?

2021-08-03 20:28 UTC, dmangum2 commented on README.md
> +3. **New revision on documentation changes that are reflected in the IG**
Note the version number pattern, like x.x.N?

2021-08-05 11:23 UTC, coxstuart commented on README.md
> +Changes must be made to the following files to version the IG. This will ensure the automatmed releases work correctly.
Fixed. Thank you.

2021-08-05 11:24 UTC, coxstuart commented on README.md
> +1. **New major versions on breaking changes**
Good suggestion.  I added that.  Please review and let me know if you think we need more.

2021-08-05 11:24 UTC, coxstuart commented on README.md
> +2. **New minor version on non-breaking IG profile changes**
Done

2021-08-05 11:24 UTC, coxstuart commented on README.md
> +3. **New revision on documentation changes that are reflected in the IG**
Done

2021-08-05 12:20 UTC, dmangum2 approved these changes

2021-08-05 13:03 UTC, kimkenna approved these changes
Great work!

2021-08-05 15:14 UTC, merged