Hiwhc 2612  add commercial,opt drug
LinuxForHealth/cdm-fhir-ig pull request #47
Opened 2021-08-03 20:12 UTC by dmangum2

Open PR to review the commercial optional HI drug claims with quite a few new examples.

2021-08-04 21:06 UTC, kimkenna reviewed
Should we generalize the description for adjudication-date a bit more? Not sure if it is OK if this seems US centric: "The date on which the payment status of the claim was adjudicated by the state."

2021-08-05 12:23 UTC, dmangum2 commented
> 
> 
> Should we generalize the description for adjudication-date a bit more? Not sure if it is OK if this seems US centric: "The date on which the payment status of the claim was adjudicated by the state."

Yea, I saw that when I copied it from the approved mapping spreadsheet. I think we drop "...by the state.". Can we make this decision or do we need to run it by SME?

2021-08-06 19:06 UTC, dmangum2 commented
> 
> 
> Should we generalize the description for adjudication-date a bit more? Not sure if it is OK if this seems US centric: "The date on which the payment status of the claim was adjudicated by the state."

Yes, I confirmed with SME's that the description can be updated & changed it.

2021-08-11 13:37 UTC, coxstuart requested changes
Nice job.  Just a couple of little things.  Still confused about why we have 2 different employer code extensions.

2021-08-11 13:37 UTC, coxstuart commented on data/extensions/ClaimExtensions.fsh
> +* value[x] only CodeableConcept
What is the difference between employee-company and employer?  Seems like 2 extensions that do he same thing.  If they are different and we need two, descriptions need to be clearer about these.

2021-08-11 13:37 UTC, coxstuart commented on data/extensions/ClaimResponseExtensions.fsh
> +Description: "The Benefit Plan on the claim item"
For consistency, would not capitalize "benefit plan" in the claim-response-benefit-plan description.

2021-08-11 13:37 UTC, coxstuart commented on data/resources/claim/CDM_Claim.fsh
> +* extension[employeeCompany] ^definition = "Customer-specific code for the company of the employee"
I see that the employeeCompany and employer are at two different levels.  They can still use the same extension, although that would mean mapping changes.

2021-08-11 13:37 UTC, coxstuart commented on data/resources/organization/CDM_Organization_Instance.fsh
> +Title:          "CDM Organization - General Hospital"
Nice catch on my spelling.  Thank you!

2021-08-11 13:37 UTC, coxstuart commented on data/resources/organization/CDM_Organization_Payer1.fsh
> +Title:          "CDM Organization - Payer 1"
Thanks for fixing my spelling

2021-08-11 13:37 UTC, coxstuart commented on data/vocabulary/AliasCodingSystems.fsh
> +Alias: YES-NO-VS = http://terminology.hl7.org/ValueSet/v2-0532
The alias should be on the codeSystem, not the valueSet.  http://terminology.hl7.org/CodeSystem/v2-0532

2021-08-11 14:10 UTC, dmangum2 commented on data/extensions/ClaimResponseExtensions.fsh
> +Description: "The Benefit Plan on the claim item"
Done

2021-08-11 14:11 UTC, dmangum2 commented on data/resources/organization/CDM_Organization_Instance.fsh
> +Title:          "CDM Organization - General Hospital"
Sure thing!

2021-08-11 14:12 UTC, dmangum2 commented on data/resources/organization/CDM_Organization_Payer1.fsh
> +Title:          "CDM Organization - Payer 1"
Sure thing!

2021-08-11 14:14 UTC, dmangum2 commented on data/vocabulary/AliasCodingSystems.fsh
> +Alias: YES-NO-VS = http://terminology.hl7.org/ValueSet/v2-0532
I was wondering about that. Corrected.

2021-08-25 16:38 UTC, dmangum2 commented on data/extensions/ClaimExtensions.fsh
> +* value[x] only CodeableConcept
After SME review, removed employee-company from claims.

2021-08-25 16:39 UTC, dmangum2 commented on data/resources/claim/CDM_Claim.fsh
> +* extension[employeeCompany] ^definition = "Customer-specific code for the company of the employee"
After review with SME's removed employeeCompany from claim.

2021-08-26 14:40 UTC, coxstuart commented on data/extensions/ClaimExtensions.fsh
> +* value[x] only CodeableConcept
Glad to see we are down to one.  The extension name and the title should match.  So title should be Employer or the extension should be EmployerCode.  I would suggest changing the title to "Employer".  

Having them different can lead to sorting issues that look odd in the IG, since it sorts on the id, but displays the title.

2021-08-26 15:06 UTC, dmangum2 commented on data/extensions/ClaimExtensions.fsh
> +* value[x] only CodeableConcept
Good catch. I made this change.

2021-08-26 15:47 UTC, coxstuart approved these changes

2021-08-26 15:50 UTC, merged