Cdm 281 extensions for coverage and claim
LinuxForHealth/cdm-fhir-ig pull request #51
Opened 2021-08-17 19:45 UTC by janglow

2021-08-20 19:31 UTC, coxstuart requested changes

2021-08-20 19:31 UTC, coxstuart commented on data/vocabulary/MajorDiagnosticCategoryCodes.fsh
> +Description:    "IBM® Health Data Connect standard major diagnostic category codes"
Are you sure we want to include Health Data Connect verbiage in the title? Is that consistent with other vocabulary items?

2021-08-20 19:31 UTC, coxstuart commented on data/extensions/ClaimExtensions.fsh
> +Description:    "Body-system or disease related groupings of clinical conditions, based on diagnosis codes"
Nitpicking...  Just not sure about the hyphen in body-system.  Body system seems better.

2021-08-20 19:31 UTC, coxstuart commented on data/extensions/ClaimExtensions.fsh
> +Description:    "The groups of related outpatient procedures"
Wordsmithing a bit here.  You can take my suggestion or leave it.  Pefer to leave out he word outpatient since that may not be true of all procedures being grouped, could have some inpatient, etc.

Descrripton:  "Groups assigned to categorize related procedures"

2021-08-20 19:31 UTC, coxstuart commented on data/extensions/EligibilityExtensions.fsh
> +Description:    "A reference to the insurance plan for this coverage"
Please leave the title with the same text as the ID.  In this case, title of "Coverage Insurance Plan".  

If you change them up, publisher sorts on the ID, but displays the title, which makes things look really odd on some of the IG pages.  Makes it look like the sort is broken.

2021-08-20 19:31 UTC, coxstuart commented on data/extensions/EligibilityExtensions.fsh
> +* valueReference only Reference(CDMInsurancePlan)
Please reference the more generic resource (InsurancePlan).  Any time we have a reference, we use the more generic type from FHIR in order to avoid other would-be implementers from being to tightly bound to our implementation.

2021-08-20 19:31 UTC, coxstuart commented on data/resources/claim/CDM_Claim.fsh
> +
Please add ^short and ^description elements to these extensions when declared on the resource.  See CapitatedServiceIndicator below for an example.  They are usually the same value (smae and the extension description).  

I know it seems very repetitiive (and it is), but it makes things appear nicely in various places in the IG.

2021-08-20 19:31 UTC, coxstuart commented on data/vocabulary/ProcedureGroupCodes.fsh
> +* #5          "Destruction, facial lesion"          "Destruction, facial lesion"
Can we line these up with tabs?

2021-08-20 19:31 UTC, coxstuart commented on data/vocabulary/ProcedureGroupCodes.fsh
> +* codes from system WHPayerProcedureGroupCodeSystem
Please remove extra spacing and add CR to end of file.

2021-08-23 21:08 UTC, janglow commented on data/extensions/ClaimExtensions.fsh
> +Description:    "Body-system or disease related groupings of clinical conditions, based on diagnosis codes"
Changed!

2021-08-23 21:09 UTC, janglow commented on data/extensions/EligibilityExtensions.fsh
> +Description:    "A reference to the insurance plan for this coverage"
Thank you - this has been changed.

2021-08-23 21:09 UTC, janglow commented on data/resources/claim/CDM_Claim.fsh
> +
Thank you - this has been changed.

2021-08-23 21:10 UTC, janglow commented on data/vocabulary/ProcedureGroupCodes.fsh
> +* codes from system WHPayerProcedureGroupCodeSystem
By extra spacing, I assume you meant the extra lines which have now been removed.  I also added a CR to the end of the file as suggested.

2021-08-23 21:11 UTC, janglow commented on data/vocabulary/ProcedureGroupCodes.fsh
> +* #5          "Destruction, facial lesion"          "Destruction, facial lesion"
yes that would certainly look better!

2021-08-23 21:11 UTC, janglow commented on data/extensions/EligibilityExtensions.fsh
> +* valueReference only Reference(CDMInsurancePlan)
Glad you explained... and yes I will make this change.

2021-08-23 21:15 UTC, janglow commented on data/extensions/ClaimExtensions.fsh
> +Description:    "The groups of related outpatient procedures"
The data I am working with only includes this type of information for outpatient procedures but I agree we don't need to make it that specific in the description and I have made the change you suggested.

2021-08-23 21:17 UTC, janglow commented on data/vocabulary/MajorDiagnosticCategoryCodes.fsh
> +Description:    "IBM® Health Data Connect standard major diagnostic category codes"
I believe this is okay as-is given there are other codesystem and valueset descriptions using the same phrasing.

2021-08-25 04:19 UTC, kimkenna reviewed
This description could be confusing: "The number of days for the month of eligibility". Is this literally the number of days for the month that the coverage is applied to (aka: there are 30 days in June)? Or is it the number of days of coverage for this member in this coverage period instance. aka: are we assuming that Coverage is only a month at a time ... which for some scenarios that's not how they will use this resource.

2021-08-25 04:19 UTC, kimkenna commented on data/extensions/ClaimExtensions.fsh
> +Description:    "Body-system or disease related groupings of clinical conditions, based on diagnosis codes"
I had the same visceral reaction but decided I might be wrong so hadn't commented :) I do concur though upon looking again!

2021-08-25 13:35 UTC, janglow commented
> This description could be confusing: "The number of days for the month of eligibility". Is this literally the number of days for the month that the coverage is applied to (aka: there are 30 days in June)? Or is it the number of days of coverage for this member in this coverage period instance. aka: are we assuming that Coverage is only a month at a time ... which for some scenarios that's not how they will use this resource.

I see what you mean about the confusion because the text says “month” and that isn’t right… it is only right for one of our scenarios.   I will change to “The number of covered days of eligibility”.  Thank you :)

2021-08-25 15:57 UTC, coxstuart commented on data/extensions/ClaimExtensions.fsh
> +Description:    "Body-system or disease related groupings of clinical conditions, based on diagnosis codes"
Still seeing body-system on my end.  Did you commit and push the change?

2021-08-25 16:04 UTC, coxstuart commented on data/extensions/ClaimExtensions.fsh
> +Description:    "Body-system or disease related groupings of clinical conditions, based on diagnosis codes"
Nevermind, see it now!

2021-08-25 16:30 UTC, coxstuart approved these changes

2021-08-25 17:35 UTC, merged