Initial ExplanationOfBenefit and example -- issue #53
LinuxForHealth/cdm-fhir-ig pull request #55
Opened 2021-08-30 17:46 UTC by janglow

2021-09-01 12:56 UTC, dmangum2 requested changes
Are there any additional examples, specific to the EOB resource that you could/should add? I didn't check, but I can if you need some help.

2021-09-01 12:56 UTC, dmangum2 commented on data/invariants/CDM_Claim_Invariant.fsh
> +Expression:	"explanationofbenefit.careTeam.sequence = explanationofbenefit.item.careTeamSequence"
Minor comment, it's easier to read if you align the text.

2021-09-01 12:56 UTC, dmangum2 commented on data/resources/claim/CDM_ExplanationOfBenefit.fsh
> +Description:    "This resource provides the list of professional services and products sent to an insurer for reimbursement along with the corresponding adjudication details. The CDMExplanationOfBene
Description doesn't seem to really convey the EOB. Take a look at https://www.hl7.org/fhir/explanationofbenefit.html

2021-09-01 12:56 UTC, dmangum2 commented on data/resources/claim/CDM_ExplanationOfBenefit.fsh
> +* procedure.extension[procedureGroup]  ^definition  = "Groups assigned to categorize related procedures"
Minor comment. Should "Groups assigned..." be plural? Maybe just "Group assigned...."

2021-09-01 12:56 UTC, dmangum2 commented on data/resources/claim/CDM_ExplanationOfBenefit_Professional_Instance.fsh
> +//* meta.extension[sourceFileId].valueString     = "e00080779"
If the sourceFileId meta isn't used, can it be removed instead of commenting it out?

2021-09-01 12:56 UTC, dmangum2 commented on data/resources/claim/CDM_ExplanationOfBenefit_Professional_Instance.fsh
> +* identifier[0].system           = "http://acmehealth.com/CodeSystem/local-claim-identifier"
identifier[0].system should probably refer to local-eob-identifier instead of local-claim-identifer (just to be consistent).

2021-09-01 12:56 UTC, dmangum2 commented on data/resources/claim/CDM_ExplanationOfBenefit_Professional_Instance.fsh
> +* item[0].adjudication[4].amount.value        = 0.00
Resequence the adjudication arrays. They will not match the approved mappings, but at least you'll not get QA errors. And you could remove the comment.

2021-09-01 12:56 UTC, dmangum2 commented on data/resources/claim/CDM_ExplanationOfBenefit_Professional_Instance.fsh
> +* item[0].adjudication[7].category             = AdjudicationCategoryCodeSystem#net-payment
remove adjudication[7] info and the comment and resequence.  This was original to the professional instance example, but I've made same changes to my work.

2021-09-01 12:56 UTC, dmangum2 commented on data/resources/claim/CDM_ExplanationOfBenefit_Professional_Instance.fsh
> +* item[0].adjudication[12].category              = AdjudicationCategoryCodeSystem#healthcare-reimbursement
Same comment as above. Resequence the adjudication[n] indexes and remove the comments.

2021-09-01 12:56 UTC, dmangum2 commented on data/resources/claim/CDM_ExplanationOfBenefit_Professional_Instance.fsh
> +* item[0].adjudication[18].category              = AdjudicationCategoryCodeSystem#penalty
Same comment as above about the adjudication indexes.

2021-09-01 12:56 UTC, dmangum2 commented on data/resources/claim/CDM_ExplanationOfBenefit_Professional_Instance.fsh
> +* item[0].adjudication[20].category              = AdjudicationCategoryCodeSystem#medicare-paid
Same comment as above about the adjudication indexes.

2021-09-01 12:56 UTC, dmangum2 commented on data/resources/claim/CDM_ExplanationOfBenefit_Professional_Instance.fsh
> +// Index 21 doesn't exist for Professional
Same comment as above about the adjudication indexes.

2021-09-01 12:56 UTC, dmangum2 commented on data/resources/claim/CDM_ExplanationOfBenefit_Professional_Instance.fsh
> +* item[0].adjudication[33].category              = AdjudicationCategoryCodeSystem#tax
Remove blank line.

2021-09-10 15:57 UTC, coxstuart commented on data/resources/claim/CDM_ExplanationOfBenefit.fsh
> +* diagnosis.extension[majorDiagnosticCategory]  ^definition = "Body system or disease related groupings of clinical conditions, based on diagnosis codes"
Please add binding to the valueset for this extension on the resource (WHPayerMajorDiagnosticCategoryValueSet (extensible)).  I know it is already on the extension, but adding it to the resource also enhances the appearance in the IG and makes it clearer to end users.

2021-09-10 15:57 UTC, coxstuart commented on data/resources/claim/CDM_ExplanationOfBenefit.fsh
> +* procedure.extension[procedureGroup]  ^definition  = "Groups assigned to categorize related procedures"
Please add binding to the valueset for this extension on the resource (WHPayerProcedureGroupValueSet (extensible)). I know it is already on the extension, but adding it to the resource also enhances the appearance in the IG and makes it clearer to end users.

2021-09-10 15:57 UTC, coxstuart commented on data/resources/claim/CDM_ExplanationOfBenefit.fsh
> +* item.extension[claimResponseItemStatus] ^definition = "The status of claim payment on claim item"
Please add binding to the valueset for this extension too.  See other comments

2021-09-10 15:57 UTC, coxstuart commented on data/resources/claim/CDM_ExplanationOfBenefit.fsh
> +* payment.extension[claimAdjustmentType] ^definition = "The code for the type of adjustment for the claim"
Please add binding to the valueset for this extension too. See other comments

2021-09-10 15:57 UTC, coxstuart commented on data/resources/claim/CDM_ExplanationOfBenefit_Professional_Instance.fsh
> +* item[0].adjudication[5].amount.value        = 25.0
On amounts with Money type like these, please include the currency as well.  Not doing so causes more QA warnings.  Just need to add .currency = CURRENCIES#USD

2021-09-10 15:57 UTC, coxstuart commented on data/resources/claim/CDM_ExplanationOfBenefit_Professional_Instance.fsh
> +* item[0].adjudication[19].amount.value          = 0.00
Add currency

2021-09-10 15:57 UTC, coxstuart commented on data/resources/claim/CDM_ExplanationOfBenefit_Professional_Instance.fsh
> +* item[0].adjudication[34].amount.value          = 25.00
Add currencies

2021-09-10 15:57 UTC, coxstuart commented on data/resources/claim/CDM_ExplanationOfBenefit_Professional_Instance.fsh
> +* payment.amount.value           = 5.00
Add currency

2021-09-21 17:50 UTC, janglow commented on data/resources/claim/CDM_ExplanationOfBenefit.fsh
> +* diagnosis.extension[majorDiagnosticCategory]  ^definition = "Body system or disease related groupings of clinical conditions, based on diagnosis codes"
Added binding -  thank you!

2021-09-21 17:50 UTC, janglow commented on data/resources/claim/CDM_ExplanationOfBenefit.fsh
> +* procedure.extension[procedureGroup]  ^definition  = "Groups assigned to categorize related procedures"
Added binding -  thank you!

2021-09-21 17:55 UTC, janglow commented on data/resources/claim/CDM_ExplanationOfBenefit.fsh
> +* item.extension[claimResponseItemStatus] ^definition = "The status of claim payment on claim item"
Actually, looking at these values I realize this extension should not be included in the EoB so I am removing it.  Same is true for the extension ClaimStatus.

2021-09-21 18:28 UTC, janglow commented on data/resources/claim/CDM_ExplanationOfBenefit_Professional_Instance.fsh
> +* item[0].adjudication[5].amount.value        = 25.0
Great add -- thank you!

2021-09-21 18:28 UTC, janglow commented on data/resources/claim/CDM_ExplanationOfBenefit_Professional_Instance.fsh
> +* item[0].adjudication[34].amount.value          = 25.00
Added #USD to all of these. :)

2021-09-21 18:29 UTC, janglow commented on data/resources/claim/CDM_ExplanationOfBenefit_Professional_Instance.fsh
> +* payment.amount.value           = 5.00
added the currency -- thank you!

2021-09-21 18:29 UTC, janglow commented on data/resources/claim/CDM_ExplanationOfBenefit_Professional_Instance.fsh
> +* item[0].adjudication[19].amount.value          = 0.00
added currency to all of these -- thank you!

2021-09-21 18:32 UTC, janglow commented on data/resources/claim/CDM_ExplanationOfBenefit.fsh
> +* payment.extension[claimAdjustmentType] ^definition = "The code for the type of adjustment for the claim"
binding added - thanks!

2021-09-22 13:39 UTC, dmangum2 commented on data/resources/claim/CDM_ExplanationOfBenefit_ForAnalytics_Drug_Instance.fsh
> +
I would resequence supportingInfo indexes to be sequentia else  you'll get IG validation warnings.

2021-09-22 13:40 UTC, dmangum2 commented on data/resources/claim/CDM_ExplanationOfBenefit_ForAnalytics_Drug_Instance.fsh
> +
Don't really need the careTeam[0] index since you only have one careTeam example.

2021-09-22 13:41 UTC, dmangum2 commented on data/resources/claim/CDM_ExplanationOfBenefit_Professional_Instance.fsh
> +
Extra blank line could be removed.

2021-09-22 13:42 UTC, dmangum2 commented on data/resources/claim/CDM_ExplanationOfBenefit_Professional_Instance.fsh
> +
Since there is only one  careTeam, could remove the index [1]. And reset the sequence=1.

2021-09-22 13:42 UTC, dmangum2 commented on data/resources/claim/CDM_ExplanationOfBenefit_Professional_Instance.fsh
> +
Since there is only one supportingInfo could remove the index [0].

2021-09-22 13:43 UTC, dmangum2 commented on data/resources/claim/CDM_ExplanationOfBenefit_Professional_Instance.fsh
> +
Could remove extra blank line.

2021-09-22 15:19 UTC, janglow commented on data/resources/claim/CDM_ExplanationOfBenefit_Professional_Instance.fsh
> +
removed extra line - thanks

2021-09-22 15:22 UTC, janglow commented on data/resources/claim/CDM_ExplanationOfBenefit_Professional_Instance.fsh
> +
good point - fixed!

2021-09-22 15:23 UTC, janglow commented on data/resources/claim/CDM_ExplanationOfBenefit_Professional_Instance.fsh
> +
fixed!

2021-09-22 15:28 UTC, janglow commented on data/resources/claim/CDM_ExplanationOfBenefit_ForAnalytics_Drug_Instance.fsh
> +
removed index 0 as suggested... also added .item.careTeamSequence = 1   which seems reasonable.

2021-09-22 15:31 UTC, janglow commented on data/resources/claim/CDM_ExplanationOfBenefit_ForAnalytics_Drug_Instance.fsh
> +
good catch -- I updated the indexes and adjusted the values for sequence even though that wasn't required it just looks better :)

2021-09-22 15:32 UTC, janglow commented on data/resources/claim/CDM_ExplanationOfBenefit_Professional_Instance.fsh
> +
fixed!

2021-09-22 18:03 UTC, dmangum2 approved these changes

2021-09-28 19:36 UTC, merged