Sushi upgrade 22
LinuxForHealth/cdm-fhir-ig pull request #71
Opened 2021-12-21 18:07 UTC by coxstuart

2022-01-14 20:21 UTC, dmangum2 requested changes
I think I've looked at all of the changes. 2 general areas to talk about:
1) using url vs.  alias for code system
2) claim sequence invariant issue - still working on logic

Thanks for working on all of this!

2022-01-14 20:21 UTC, dmangum2 commented on README.md
> +- data/package.json (obsolete, don't need to do this one anymore)
Do you need line 142 since the comment says it's obsolete?

2022-01-14 20:21 UTC, dmangum2 commented on data/elements/WorkAddress.fsh
> -Profile:        WorkAddress
What happened to this profile? Was it merged with something else?

2022-01-14 20:21 UTC, dmangum2 commented on data/input/fsh/resources/claim/CDM_ExplanationOfBenefit.fsh
> +* priority                from 	http://terminology.hl7.org/ValueSet/process-priority (example)
Yea, this got rid of that error!

2022-01-14 20:21 UTC, dmangum2 commented on data/input/fsh/resources/observation/CDM_Observation_Instance.fsh
> +* identifier[0].assigner.display = "Acme Health - EMR1"
Don't really index identifier index [0] since there is only one. No big deal, but I've been trying to be consistent.

2022-01-14 20:21 UTC, dmangum2 commented on data/input/fsh/resources/patient/CDM_PatientDeceased_Instance.fsh
> +* maritalStatus.coding = http://acme-health.com/CodeSystem/local-marital-status#Married
Good catch.

2022-01-14 20:21 UTC, dmangum2 commented on data/input/ignoreWarnings.txt
> +# Client-specific code systems used in examples cannot be validated by the FHIR IG Publisher
We should probably document (where?) that if we add a client-specific code system used in examples, it needs to be added to this file and also check QA report before checking-in code. Should this info be added to github?

2022-01-14 20:21 UTC, dmangum2 commented on data/input/fsh/resources/eligibility/CDM_Eligibility_Instance.fsh
> +* entry[PractitionerRole].resource = CDMPractitionerRole-Enrollment
Should title also be changed? Title:    "CDM PractitionerRole - Payer" --> "CDM PractitionRole - Enrollment"

2022-01-14 20:21 UTC, dmangum2 commented on data/input/fsh/resources/practitioner/CDM_PractitionerRole.fsh
> +Description:      "IBM Health Data Connect Common Data Model definition of what fields we currently define for a practitioner role"
Add Title (looks like it was removed).

2022-01-14 20:21 UTC, dmangum2 commented on data/input/fsh/resources/practitioner/CDM_PractitionerRole_Enrollment_Instance.fsh
> +Title:          "CDM PractitionerRole - Payer"
Change Title to "CDM PractitionerRole - Enrollment"?

2022-01-14 20:21 UTC, dmangum2 commented on data/input/fsh/resources/quality-measure/QualityMeasurePractionerReport_Instance.fsh
> +// This trick prevents QA broken link errors im the IG, without having to have too many examples
Interesting.
Typo "...errors "im" the IG, ..."

2022-01-14 20:21 UTC, dmangum2 commented on data/input/fsh/vocabulary/PlaceOfServiceCodes.fsh
> +* codes from system https://www.cms.gov/Medicare/Coding/place-of-service-codes/Place_of_Service_Code_Set
General comment, are we replacing alias's with full url string in the vocabulary files? I've been using the alias value.

2022-01-14 20:21 UTC, dmangum2 commented on data/sushi-config.yaml
> +descrption: Alvearie FHIR Profiles
Typo "descrption"

2022-01-14 20:21 UTC, dmangum2 commented on data/sushi-config.yaml
> +copyrightYear: 2021+
Change copyrightYear = 2022+ ?

2022-01-21 07:25 UTC, coxstuart commented on README.md
> +- data/package.json (obsolete, don't need to do this one anymore)
Left if there in case others were still thinking there were 3 places to update it

2022-01-21 07:25 UTC, coxstuart commented on data/elements/WorkAddress.fsh
> -Profile:        WorkAddress
Was never in use.  Old relic

2022-01-21 07:29 UTC, coxstuart commented on data/input/fsh/vocabulary/PlaceOfServiceCodes.fsh
> +* codes from system https://www.cms.gov/Medicare/Coding/place-of-service-codes/Place_of_Service_Code_Set
Aliases don't work when defining the valueset.  They should, but they cause warnings / errors on the QA page.

2022-01-21 07:30 UTC, coxstuart commented on data/sushi-config.yaml
> +descrption: Alvearie FHIR Profiles
Great catch, fixing that now!

2022-01-21 07:30 UTC, coxstuart commented on data/sushi-config.yaml
> +copyrightYear: 2021+
I think 2021+, since first release was 2021

2022-01-21 07:44 UTC, coxstuart commented on data/input/fsh/resources/practitioner/CDM_PractitionerRole_Enrollment_Instance.fsh
> +Title:          "CDM PractitionerRole - Payer"
Yep, good catch

2022-01-21 14:50 UTC, dmangum2 commented
> I think I've looked at all of the changes. 2 general areas to talk about:
> 
>     1. using url vs.  alias for code system
> 
>     2. claim sequence invariant issue - still working on logic
> 
> 
> Thanks for working on all of this!

Followup 1/21/2022- 
1) The alias was generating warnings so changed to use URL. Need to remember to check QA report after any new changes.
2) Removing the invariant until it can be resolved.

2022-01-21 17:02 UTC, dmangum2 approved these changes
Requested changes look good.

2022-01-21 18:34 UTC, kimkenna approved these changes
Thanks for addressing the comments I had to you in slack. I approve of this PR! Great work!

2022-01-21 20:42 UTC, merged