Basic resource Review
LinuxForHealth/cdm-fhir-ig pull request #82
Opened 2022-06-01 20:25 UTC by dmangum2

2022-06-02 20:19 UTC, coxstuart requested changes

2022-06-02 20:19 UTC, coxstuart commented on data/input/fsh/vocabulary/WhBasicResourceTypeCodeSystem.fsh
> +Id:             wh-basic-resource-type
wh- prefixes are a problem throughout.  In discussing this with @kimkenna, she was suggesting that we keep them for now, since that is a big breaking change that could impact many teams.

She said that we cound "repurpose" the wh- acronym, so it could mean something else, not specifically anything with watson in it.  wh = Whole Health came to mind.

That said, I'm ok with adding more now.  If we change it later, using hdc- throughout might make for sense.  For now though, I think using wh- is ok.

2022-06-02 20:19 UTC, coxstuart commented on data/input/fsh/vocabulary/WhBasicResourceTypeCodeSystem.fsh
> +* codes from system BASIC-RESOURCE-TYPE
Don't use alias when pulling in system codes.  Replace BASIC-RESOURCE-TYPE with system url (http://terminology.hl7.org/CodeSystem/basic-resource-type).  In short, sushi or the ig publisher (or both), don't like aliases here.  See ClaimSupportingInfoCategoryValueSet for another example.

I don't remember what the error was, but I had to change a bunch of these a couple of updates back to git rid of some IG errors from Aliases used in this way.  Should work, but the tools don't like it.

2022-06-03 18:56 UTC, dmangum2 commented on data/input/fsh/vocabulary/WhBasicResourceTypeCodeSystem.fsh
> +* codes from system BASIC-RESOURCE-TYPE
Hi - I tried and still get the warning.
ValueSet.where(id = 'wh-basic-resource-type') | warning | Error from server: Unable to provide support for code system http://hl7.org/fhir/ValueSet/basic-resource-type

2022-06-06 15:04 UTC, coxstuart approved these changes

2022-06-06 15:51 UTC, merged