#26 - Update urls to linuxforhealth.org
LinuxForHealth/cdm-fhir-ig pull request #94
Opened 2022-09-08 20:24 UTC by coxstuart

2022-11-02 14:04 UTC, dmangum2 requested changes
A few comments. Most around the URL names. We can chat once you have time to review.

2022-11-02 14:04 UTC, dmangum2 commented on README.md
> +For release history of this IG, view the [release page](https://github.com/LinuxForHealth/alvearie-fhir-ig/releases). Each release includes:
Why are we still using alvearie-fhir-ig instead of linuxforhealth.org/fhir/cdm/releases?

2022-11-02 14:04 UTC, dmangum2 commented on data/input/fsh/elements/ProcessMeta.fsh
> +* tag[SourceClassificationTag].system = "http://linuxforhealth.org/platform/process-meta-source-classification"
/platform/ ? What's the new directory structure?

2022-11-02 14:04 UTC, dmangum2 commented on data/input/fsh/resources/communication/Engagement_CommunicationRequest_Instance.fsh
> +* meta.source = "http://linuxforhealth.org/platform/engagement"
http://linuxforhealth.org/platform - what does this mean to have a different url?

2022-11-02 14:04 UTC, dmangum2 commented on data/input/fsh/resources/communication/Engagement_CommunicationRequest_Instance.fsh
> +* identifier[0].system = "http://linuxforhealth.org/platform/engagement-communication-request"
platform in the url?

2022-11-02 14:04 UTC, dmangum2 commented on data/input/fsh/resources/detected-issue/CareGapDetectedIssue_Instance.fsh
> +* meta.source = "http://linuxforhealth.org/platform/engagement-measure-cohort"
Maybe I understand now. http://linuxforheath.org/platform/ is a fictional location for the data?

2022-11-02 14:04 UTC, dmangum2 commented on data/input/fsh/resources/organization/CDM_Organization_HDC.fsh
> +* meta.source = "http://linuxforhealth.org/platform/platform"
http://linuxforhealth.org/platform/platform looks strange.  Above just had http://linuxforhealth.org/platform (drop the 2nd platform) to be consistent. ok?

data/input/fsh/resources/organization/CDM_Organization_CommunicationVendor1.fsh

2022-11-02 14:04 UTC, dmangum2 commented on data/input/fsh/vocabulary/IdentifierTypeCodes.fsh
> +Description:    "Extended set of Identifier type code for LinuxForHealth Common Data Model resources"
I think the word code should be plural -> "...Identifier type codes..."

2022-11-02 14:04 UTC, dmangum2 commented on data/input/fsh/vocabulary/WhPayerCoverageClassCodes.fsh
> +Description:    "LinuxForHealth standard code for the coverage class"
In previous code system descriptions, you described as "Payer codes for...." and removed the LinuxForHealth word, but here you kept it. To be consistent should it be removed and changed to "Payer codes for the coverage class"?

2022-11-02 14:04 UTC, dmangum2 commented on data/input/fsh/vocabulary/WhPayerCoverageClassCodes.fsh
>  * codes from system COVERAGE-CLASS
Similar wording for the value set description.

2022-11-02 14:04 UTC, dmangum2 commented on data/input/fsh/vocabulary/WhPayerEmployeeStatusCodes.fsh
>  * ^caseSensitive = true
Description should be "Payer employee status **codes** for the claims". The old description wasn't correct either.

2022-11-02 14:04 UTC, dmangum2 commented on data/input/fsh/vocabulary/WhPayerMedicareCoverageCodes.fsh
> +Description:    "Value set containting payer coees for the type of Medicare coverage, if any, for the person"
Typo -> coees

2022-11-02 14:04 UTC, dmangum2 commented on data/input/fsh/vocabulary/WhPayerProviderTypeCodes.fsh
> +Description:    "LinuxForHealth standard values for practitioner role type"
Drop the LinuxForHealth and use Payer standard values ....?

2022-11-02 14:04 UTC, dmangum2 commented on data/input/fsh/vocabulary/WhPayerProviderTypeCodes.fsh
> +Description:    "LinuxForHealth standard values for organization type"
Drop the LinuxForHealth and use Payer standard values for ...?

2022-11-02 14:04 UTC, dmangum2 commented on data/input/pagecontent/downloads.md
> +Download and copy this Java JAR file to an LinuxForHealth FHIR® Server to make LinuxForHealth FHIR IG profiles available to the FHIR Registry for profile validation.  See [LinuxForHealth FHIR® Server
Grammar?  I think it should be "...JAR file to **a** LinuxForHealth..."

2022-11-02 14:04 UTC, dmangum2 commented on data/input/pagecontent/index.md
> +For release history of this IG, view the [release page](https://github.com/LinuxForHealth/alvearie-fhir-ig/releases) on our GitHub repo. Each release includes:
Are we keeping /alvearie-fhir-ig/ in the url?

2022-11-02 14:04 UTC, dmangum2 commented on package.json
> +  "url": "http://fhir.linuxforhealth.org/cdm",
Are these the URL's we are waiting for Lee/Ted to create?

2022-11-02 14:04 UTC, dmangum2 commented on package.json
>    "license": "CC0-1.0"
Good idea to make the author generic!

2022-11-02 14:04 UTC, dmangum2 commented on data/input/fsh/vocabulary/WhPayerTanBenefitCodes.fsh
>  Description:     "Temporary Assistance for Needy Families (TANF) benefit value set for the person"
Alignment comment on row 14. Delete space before "Temporary...."

2022-11-02 14:04 UTC, dmangum2 commented on package.json
>      "build_snapshot": "mkdirp src/main/resources/com/ibm/fhir/cdm && tar -C src/main/resources/com/ibm/fhir/cdm/ -xf build/output/package.tgz && mvn clean install",
Do we need to rename/change the folder to remove/change "ibm"

2022-11-02 15:32 UTC, coxstuart commented on README.md
> +For release history of this IG, view the [release page](https://github.com/LinuxForHealth/alvearie-fhir-ig/releases). Each release includes:
That is because the repo is named alvearie-fhir-ig when Lee created it.  We could have him rename it, or setup a new repo.  fhir-ig might be a better name.

2022-11-07 17:03 UTC, coxstuart commented on data/input/fsh/resources/communication/Engagement_CommunicationRequest_Instance.fsh
> +* meta.source = "http://linuxforhealth.org/platform/engagement"
This is an example instance.  This should be a source identifies the software or process generating the request.  Since we don't have any system to reference here, I went with generic /platform/?  Maybe we should use something like "comm-platform" to be more specific?

2022-11-07 17:03 UTC, coxstuart commented on data/input/fsh/resources/communication/Engagement_CommunicationRequest_Instance.fsh
> +* identifier[0].system = "http://linuxforhealth.org/platform/engagement-communication-request"
This is an example instance.  This should be a uri the identifies the software or process generating the request.  Since we don't have any system to reference here, I went with generic /platform/?  Maybe we should use something like "comm-platform" to be more specific?

2022-11-07 17:11 UTC, coxstuart commented on data/input/fsh/resources/detected-issue/CareGapDetectedIssue_Instance.fsh
> +* meta.source = "http://linuxforhealth.org/platform/engagement-measure-cohort"
It's a generic placehoder for a system of record.  Maybe comm-platform or l4h-comm-platform would be better here?

2022-11-07 17:12 UTC, coxstuart commented on data/input/fsh/resources/organization/CDM_Organization_HDC.fsh
> +* meta.source = "http://linuxforhealth.org/platform/platform"
Yes, I agree.  Will drop the 2nd one.

2022-11-07 17:18 UTC, coxstuart commented on data/input/fsh/elements/ProcessMeta.fsh
> +* tag[SourceClassificationTag].system = "http://linuxforhealth.org/platform/process-meta-source-classification"
I still need to look at this one.  Will come back to it once we iron out the "platform" thing.  But at first pass, this doesn't look right.

2022-11-07 17:18 UTC, coxstuart commented on data/input/pagecontent/index.md
> +For release history of this IG, view the [release page](https://github.com/LinuxForHealth/alvearie-fhir-ig/releases) on our GitHub repo. Each release includes:
That is because the repo is named alvearie-fhir-ig when Lee created it. We could have him rename it, or setup a new repo. fhir-ig might be a better name.

2022-11-07 17:20 UTC, coxstuart commented on package.json
> +  "url": "http://fhir.linuxforhealth.org/cdm",
Yes, they are. Goal is for the IG urls to resolve.  Could change after that, depending on where they put it (hopefully not).

2022-11-07 17:20 UTC, coxstuart commented on package.json
>    "license": "CC0-1.0"
Yeah!  I thought so.

2022-11-07 17:33 UTC, coxstuart commented on data/input/fsh/vocabulary/WhPayerTanBenefitCodes.fsh
>  Description:     "Temporary Assistance for Needy Families (TANF) benefit value set for the person"
Done

2022-11-07 17:36 UTC, coxstuart commented on package.json
>      "build_snapshot": "mkdirp src/main/resources/com/ibm/fhir/cdm && tar -C src/main/resources/com/ibm/fhir/cdm/ -xf build/output/package.tgz && mvn clean install",
We can't do that until we get the tests working with new version L4H builid of the FHIR server.  I tried doing that and ran into some other issue that we will need help from Lee on.  I think we should get these changes out, then circle back for that, but let's discuss.

2022-11-08 20:37 UTC, dmangum2 commented on README.md
> +For release history of this IG, view the [release page](https://github.com/LinuxForHealth/alvearie-fhir-ig/releases). Each release includes:
This is only in the readme so we'll address the name address this when the URL is changed.

2022-11-08 20:43 UTC, dmangum2 commented on data/input/fsh/elements/ProcessMeta.fsh
> +* tag[SourceClassificationTag].system = "http://linuxforhealth.org/platform/process-meta-source-classification"
This will be corrected to have system = processMetaSourceClassification

2022-11-08 20:45 UTC, dmangum2 commented on data/input/fsh/resources/communication/Engagement_CommunicationRequest_Instance.fsh
> +* meta.source = "http://linuxforhealth.org/platform/engagement"
This is ok as it's just an example.

2022-11-08 20:47 UTC, dmangum2 commented on package.json
>      "build_snapshot": "mkdirp src/main/resources/com/ibm/fhir/cdm && tar -C src/main/resources/com/ibm/fhir/cdm/ -xf build/output/package.tgz && mvn clean install",
ok

2022-11-08 21:05 UTC, dmangum2 commented on data/input/fsh/resources/communication/Engagement_CommunicationRequest_Instance.fsh
> +* identifier[0].system = "http://linuxforhealth.org/platform/engagement-communication-request"
Now that I understand I'm ok with leaving as is.

2022-11-08 21:06 UTC, dmangum2 commented on data/input/fsh/resources/detected-issue/CareGapDetectedIssue_Instance.fsh
> +* meta.source = "http://linuxforhealth.org/platform/engagement-measure-cohort"
I'm ok with leaving as is.

2022-11-08 21:06 UTC, dmangum2 commented on data/input/pagecontent/index.md
> +For release history of this IG, view the [release page](https://github.com/LinuxForHealth/alvearie-fhir-ig/releases) on our GitHub repo. Each release includes:
Ok, let's ask Lee to rename after we complete these changes.

2022-11-08 21:07 UTC, dmangum2 commented on package.json
> +  "url": "http://fhir.linuxforhealth.org/cdm",
Ok, we'll verify once the URL has been created.

2022-11-09 14:39 UTC, dmangum2 requested changes

2022-11-09 14:39 UTC, dmangum2 commented on data/input/fsh/resources/organization/CDM_Organization_CommunicationVendor1.fsh
> +* meta.source = "http://linuxforhealth.com/platform"
Other places it's "http://linuxforhealth.org/platform". Should it be changed to be consistent?

2022-11-09 14:39 UTC, dmangum2 commented on data/input/fsh/resources/organization/CDM_Organization_CommunicationVendor1.fsh
> +* identifier[0].system = "http://linuxforhealth.com/platform/communication-vendor"
Other places it's "http://linuxforhealth.org/platform/...". Should it be changed to be consistent?

2022-11-09 16:41 UTC, dmangum2 approved these changes

2022-11-10 15:56 UTC, merged